### ISSUE TITLE
Update Docs to 3.0+

### ISSUE THREAD

**Issue by SpecificallyGravity** [beer-garden/beer-garden.io#64]
Documentation needs to be brought into sync with version 3.

Specifically referring to the docs that are published [here](https://beer-garden.io/docs/plugins/plugin-developer-guide/).

**Comment by hazmat345** [comment]
So I've been trying to dig though all of our docs and they've gotten ... disorganized.

I'm a big fan of the [Divio](https://documentation.divio.com/) way to approach different types of documentation. I think we already have a lot of this stuff, it's not just organized in a way that would be helpful to a potential customer. So my plan is to organize this as I'm updating for 3.0.

**Comment by scott-taubman** [comment]
This is done-ish.
